import 'package:flutter/material.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_text_styles.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms of Service'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'HangBug Terms of Service',
              style: AppTextStyles.displaySmall.copyWith(
                fontSize: 22,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              'Effective Date: September 2026',
              style: AppTextStyles.bodySmall.copyWith(color: AppColors.textSecondary),
            ),
            const SizedBox(height: 20),
            _buildSection(
              title: '1. Acceptance of Terms',
              body:
                  'By accessing or using the HangBug mobile application or web services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.',
            ),
            _buildSection(
              title: '2. User Accounts',
              body:
                  'You must provide accurate and complete registration information. You are solely responsible for maintaining the confidentiality of your credentials and for all activities that occur under your account.',
            ),
            _buildSection(
              title: '3. Academic Integrity & Quizzes',
              body:
                  'HangBug quizzes and assessments are designed to measure authentic software engineering and web development comprehension. Users agree not to cheat, exploit vulnerabilities, or use automated bots to artificially complete quizzes or manipulate leaderboard statistics.',
            ),
            _buildSection(
              title: '4. Certification Credentialing',
              body:
                  'Certificates generated by HangBug represent completion of specific assessments with an 80% or greater score. HangBug reserves the right to revoke any certificate obtained through fraudulent or abusive means.',
            ),
            _buildSection(
              title: '5. Intellectual Property',
              body:
                  'All quiz questions, explanations, UI graphics, and proprietary software are the intellectual property of HangBug and its licensors. You may not scrape, republish, or redistribute our proprietary questions without express written consent.',
            ),
            _buildSection(
              title: '6. Disclaimer of Warranties',
              body:
                  'HangBug is provided "as is" and "as available" without warranties of any kind. While we strive for accuracy in all technical questions, technology stacks evolve rapidly and we do not warrant that all content is free from typographical or technical errors.',
            ),
            _buildSection(
              title: '7. Governing Law & Contact',
              body:
                  'These Terms shall be governed by and construed in accordance with applicable laws. For inquiries regarding these terms, please contact legal@hangbug.com or visit https://hangbug.vercel.app.',
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }

  Widget _buildSection({required String title, required String body}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: AppTextStyles.labelBold.copyWith(
              fontSize: 16,
              color: AppColors.primary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            body,
            style: AppTextStyles.bodyMedium.copyWith(
              color: AppColors.textPrimary,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
